### PyTorch-NLP

In [1]:
#!pip install torchtext

In [1]:
import os
import re
import numpy as np
import pandas as pd
import utils.preprocessing

#### data

In [2]:
column_names=['category','title','content']
df=pd.read_csv('data/train.csv',names=column_names,header=None,delimiter=',')
df=df.sample(frac=1,random_state=1337)
mapping={1:'world',2:'sports',3:'business',4:'sci/tech'}
df=df.replace({'category':mapping})
df.head()

category                                              title  \
86110  sci/tech     Oracle to drop PeopleSoft suit if tender fails   
74390  sci/tech  NTT DoCoMo, IBM, Intel team to secure mobile d...   
77491  sci/tech    Election Is Crunch Time for U.S. Secret Service   
27497    sports   Former Celtic striker Larsson on Barcelona bench   
47492     world      Four Suicides Linked to Child Porn Probe (AP)   

                                                 content  
86110  Oracle Corp. notified Delaware's Court of Chan...  
74390  With an eye towards making mobile devices and ...  
77491  With just days to go before the U.S. president...  
27497  Henrik Larsson was left on the bench by Barcel...  
47492  AP - The government will press on with a child...

Data come feom https://course20.fast.ai/datasets.html

For this example:
- category is a target
- title is an input

In [3]:
df.category.value_counts()

sci/tech    30000
sports      30000
world       30000
business    30000
Name: category, dtype: int64

## pre-processing

#### dummy encode labels

In [3]:
encoded_y,labels=utils.preprocessing.dummy_encode_labels(df,'category')
print(labels)
print(encoded_y)

['business' 'sci/tech' 'sports' 'world']
[[0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 ...
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [5]:
df['category'].iloc[0]

'sci/tech'

In [6]:
encoded_y[0]

array([0., 1., 0., 0.], dtype=float32)

#### tokenize and set fixed sequence lengths

In [4]:
processed_docs,tokenizer=utils.preprocessing.tokenize_and_pad_docs(df,'title')

vocabulary size: 39580
number of headlines: 120000


In [4]:
df['title'].loc[0]

'Wall St. Bears Claw Back Into the Black (Reuters)'

In [5]:
processed_docs[0]

array([ 108,    2,  303,  120,  482,  607, 4460,  909,    1,    1,    1,
          1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
          1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
          1,    1,    1,    1,    1,    1,    1])

#### import word embeddings

In [5]:
embedding_matrix=utils.preprocessing.get_word_embeddings(tokenizer,'/embeddings')

downloading word vectors...


CalledProcessError: Command '['wget -NP /embeddings https://dl.fbaipublicfiles.com/fasttext/vectors-crawl/cc.en.300.vec.gz']' returned non-zero exit status 1.